"use strict";

///////////////////////////////////////
// Modal window

const modal = document.querySelector(".modal");
const overlay = document.querySelector(".overlay");
const btnCloseModal = document.querySelector(".btn--close-modal");
const btnsOpenModal = document.querySelectorAll(".btn--show-modal");

const openModal = function (e) {
  // Prevent the default behaviour of the page to be automatic scrolled up whenever the open account button is clicked
  e.preventDefault();

  modal.classList.remove("hidden");
  overlay.classList.remove("hidden");
};

const closeModal = function () {
  modal.classList.add("hidden");
  overlay.classList.add("hidden");
};

// Using forEach() to loop over the nodeList returned after the querySelectorAll so as to add an event listener to both "open account button" and "open your free account today!" button
btnsOpenModal.forEach((btn) => btn.addEventListener("click", openModal));

btnCloseModal.addEventListener("click", closeModal);
overlay.addEventListener("click", closeModal);

document.addEventListener("keydown", function (e) {
  if (e.key === "Escape" && !modal.classList.contains("hidden")) {
    closeModal();
  }
});

// TODO: Implementing smooth scrolling
const btnScrollTo = document.querySelector(".btn--scroll-to");
const section1 = document.querySelector("#section--1");

btnScrollTo.addEventListener("click", function () {
  //Scroll the page until section1 becomes visible, using a smooth scrolling animation.
  section1.scrollIntoView({ behavior: "smooth" });
  // section1.scrollIntoView(); //Without the behavior: "smooth" , the browser jumps directly to the section
});

// NOTE: Types of events and event handler

// An event is basically a signal that is generated by a dumb node, and a signal means something has happened for example.. click somewhere or mouse is moving etc

// Mouse enter event - this is like a mouse hover event in css, so it's triggered whenever the mouse enter/hover a certain element

const h1 = document.querySelector("h1");

// h1.addEventListener("mouseenter", function () {

// alert("Great! You're reading the heading!");

// });

// We can also directly add event to an element by using onevent property, although this is kind of the old shool way on listening to an event.. so usually using addEvent listener

// h1.onmouseenter = function () {

// alert("Great! You're reading the heading!");

// };

// We can also use the addEventlistener() and listen and remove the event listener when a certain even occur by using removeEventListener()

// But first we need to export the call back function outside.. consider below

// This help us to only listen for event once

const alertH1 = function () {
  alert("Great! You're reading the heading!");

  // This remove the listener after it has happened once, and it's not necessary to remove the event here , we can remove the event anywhere

  // h1.removeEventListener("mouseenter", alertH1);
};

h1.addEventListener("mouseenter", alertH1);

// Let's remove the event after 3 seconds has passed

setTimeout(function () {
  h1.removeEventListener("mouseenter", alertH1);
}, 3000);

// There are 3 ways of handling event the firat one is by using addEventListener(), the second one is onevent , and the last one is by direclty attaching the event on html element like <h1 onclick="alert('The head is clicked')" > This is heading</h1>
